// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChsFNqYVqlLuVeRY01uUd4ACnAz0apZUw',
    appId: '1:868215185227:web:a264d9ab96c319bc0352ce',
    messagingSenderId: '868215185227',
    projectId: 'flutter-firebase-sns-app',
    authDomain: 'flutter-firebase-sns-app.firebaseapp.com',
    storageBucket: 'flutter-firebase-sns-app.appspot.com',
    measurementId: 'G-2SF20FJ393',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXYMwa0H7LEEI8psk_rFWIoOq2_e1g7wQ',
    appId: '1:868215185227:android:e3dcc26aebd5498e0352ce',
    messagingSenderId: '868215185227',
    projectId: 'flutter-firebase-sns-app',
    storageBucket: 'flutter-firebase-sns-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOnnPLBW149V6oxbiYQK_of5TBSTzei9A',
    appId: '1:868215185227:ios:11842e7ac221efea0352ce',
    messagingSenderId: '868215185227',
    projectId: 'flutter-firebase-sns-app',
    storageBucket: 'flutter-firebase-sns-app.appspot.com',
    iosClientId: '868215185227-nu6q8nva1974ha09io5t182t5ikbfns5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSnsApp',
  );
}
